// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhfFb4XMvCKwskng3kPuwKLmXPF6voXQQ',
    appId: '1:902061235963:web:e3e2223e62c094e11e5a5e',
    messagingSenderId: '902061235963',
    projectId: 'helpinblood-8b290',
    authDomain: 'helpinblood-8b290.firebaseapp.com',
    databaseURL: 'https://helpinblood-8b290-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'helpinblood-8b290.appspot.com',
    measurementId: 'G-1FJQ1KEX4Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpNkjvJsurQ_7GlIlrkblf5XgYWRxzAX4',
    appId: '1:902061235963:android:36e9c98695c4aafa1e5a5e',
    messagingSenderId: '902061235963',
    projectId: 'helpinblood-8b290',
    databaseURL: 'https://helpinblood-8b290-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'helpinblood-8b290.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCklWgx6XA0nn135FC_850WcEknPOu52Y',
    appId: '1:902061235963:ios:c435d5833fc4a5fa1e5a5e',
    messagingSenderId: '902061235963',
    projectId: 'helpinblood-8b290',
    databaseURL: 'https://helpinblood-8b290-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'helpinblood-8b290.appspot.com',
    iosClientId: '902061235963-ionarid64vau0kjk8dk1cf909i1cmj1m.apps.googleusercontent.com',
    iosBundleId: 'com.example.bloodBridge',
  );
}
